### ISSUE TITLE
Role_Privilege importation breaks the Aijar Activator 

### ISSUE THREAD

**Issue by dbaluku** [METS-Programme/openmrs-module-aijar#451]
https://github.com/METS-Programme/openmrs-module-aijar/blob/bedbddcc32ccf523000dafa84b9a6c8f70dca521/api/src/main/java/org/openmrs/module/aijar/AijarActivator.java#L140

**Comment by slubwama** [comment]
@dbaluku did you pull the latest of Aijar??

**Comment by dbaluku** [comment]
@slubwama  I did
